import { z } from "zod";

// User messages capped at 500 chars (input limit). Assistant messages are
// generated by our own API so they can be longer — capped at 4096 to bound
// history size without rejecting legitimate multi-turn conversations.
const UserMessageSchema = z.object({
  role: z.literal("user"),
  content: z
    .string()
    .min(1)
    .max(500)
    .transform((s) => s.trim())
    .pipe(z.string().min(1)),
});

const AssistantMessageSchema = z.object({
  role: z.literal("assistant"),
  content: z
    .string()
    .min(1)
    .max(4096)
    .transform((s) => s.trim())
    .pipe(z.string().min(1)),
});

export const MessageSchema = z.discriminatedUnion("role", [
  UserMessageSchema,
  AssistantMessageSchema,
]);

export const RequestSchema = z.object({
  messages: z.array(MessageSchema).min(1).max(30),
});

export type ValidatedMessage = z.infer<typeof MessageSchema>;
export type ValidatedRequest = z.infer<typeof RequestSchema>;

export function validateRequest(
  body: unknown
): { success: true; data: ValidatedRequest } | { success: false; error: string } {
  const result = RequestSchema.safeParse(body);
  if (!result.success) {
    return { success: false, error: "invalid_request" };
  }
  return { success: true, data: result.data };
}

export function sanitizeMessages(messages: ValidatedMessage[]): ValidatedMessage[] {
  // Filter to only user/assistant (already enforced by schema, belt-and-suspenders)
  const filtered = messages.filter(
    (m) => m.role === "user" || m.role === "assistant"
  );
  // Trim to last 20 entries (10 conversation turns)
  return filtered.slice(-20);
}

// Exact origin whitelist for CORS — addresses review concern: all 3 reviewers flagged
// endsWith() as bypassable (e.g., "evil-jackcutrara.com" would pass).
// Uses URL parsing for safe comparison.
const ALLOWED_ORIGINS = [
  "https://jackcutrara.com",
  "https://www.jackcutrara.com",
];

// Cloudflare Workers preview hostname. Only subdomains of this hostname
// (preview deployments of THIS Worker) pass CORS — not every *.workers.dev site.
// The {worker_name}.{account_subdomain} prefix is Cloudflare-assigned at
// account creation + Worker name and is load-bearing: it prevents another
// Cloudflare user from registering a colliding Worker name and bypassing
// this check. If the Worker is ever renamed, update this constant in lockstep.
// VALUE captured from first *.workers.dev preview deploy on 2026-05-10
// (Phase 17 Plan 17-02 Task 3 cutover; Worker = jack-cutrara-portfolio,
// account subdomain = jackcutrara).
const WORKERS_PREVIEW_SUFFIX = ".jackcutrara.workers.dev";

// WR-04 (Phase 17 review): localhost / loopback origins are allowed ONLY in
// DEV builds. The previous version returned true unconditionally — including
// in the deployed Worker — which weakened the S9 CORS allowlist as a
// defense-in-depth control. Browser same-origin policy prevents direct
// exploitation, but non-browser clients (curl, server-side relays, malicious
// extensions) can spoof Origin headers freely, so the production endpoint
// silently accepted them. Vite/Astro tree-shakes the DEV-branch disjunction
// in production builds (each operand is a statically-replaced literal: DEV
// becomes `false`, MODE becomes `"production"`, process.env.NODE_ENV becomes
// `"production"`), so the loopback bypass emits zero bytes in the deployed
// Worker bundle. IPv6 loopback [::1] is included for consistency (also
// DEV-only).
//
// Plan 17-08 Task 2-ALPHA (Rule 3 inline deviation, 2026-05-11): broadened
// from the single signal `import.meta.env.DEV` to a three-signal disjunction
// because the @astrojs/cloudflare adapter does NOT statically replace
// `import.meta.env.DEV` in SSR routes under `astro dev`. The single-signal
// form evaluated falsy in the dev SSR runtime, causing every POST /api/chat
// from http://localhost:4321 to return 403 Forbidden (Plan 17-08 deploy-gate
// UAT regression on 2026-05-11). The three signals together cover:
//   1. `import.meta.env.DEV === true` — Vitest (sets DEV=true by default,
//      preserving every existing security.test.ts assertion) and Vite client
//      bundles under `astro dev` (statically replaced).
//   2. `import.meta.env.MODE === "development"` — @astrojs/cloudflare SSR
//      routes under `astro dev` (MODE is reliably set even when DEV is not
//      statically replaced).
//   3. `process.env.NODE_ENV === "development"` — pure-Node fallback for
//      environments where neither import.meta.env signal is populated.
// All three operands are statically replaced to literal `false` /
// `"production"` during production `astro build`, so the entire branch is
// tree-shaken from the deployed Worker bundle — verifiable by post-build
// grep on dist/_worker.js (no `ALLOW_LOOPBACK` residue). Production CORS
// remains exactly as authored: deployed Worker continues to reject
// Origin=http://localhost:4321 (defense-in-depth against Origin spoofing).
const ALLOW_LOOPBACK =
  import.meta.env.DEV === true ||
  import.meta.env.MODE === "development" ||
  (typeof process !== "undefined" && process.env?.NODE_ENV === "development");

export function isAllowedOrigin(origin: string | null): boolean {
  if (!origin) return true; // No origin header = same-origin or non-browser
  let url: URL;
  try {
    url = new URL(origin);
  } catch {
    return false; // Malformed origin
  }
  // DEV-only: allow loopback hosts. URL parsers normalize [::1] in Origin
  // headers to "[::1]" (square brackets preserved); list all three forms.
  if (
    ALLOW_LOOPBACK &&
    (url.hostname === "localhost" ||
      url.hostname === "127.0.0.1" ||
      url.hostname === "[::1]")
  ) {
    return true;
  }
  // Allow preview subdomains of the Worker's workers.dev hostname (https only).
  // Require exactly one non-empty label before the suffix — this rejects the
  // apex `jackcutrara.workers.dev` and empty-label forms like
  // `..jackcutrara.workers.dev` that some URL parsers normalize inconsistently.
  if (url.protocol === "https:" && url.hostname.endsWith(WORKERS_PREVIEW_SUFFIX)) {
    const prefix = url.hostname.slice(0, -WORKERS_PREVIEW_SUFFIX.length);
    if (prefix.length > 0 && !prefix.endsWith(".")) return true;
  }
  return ALLOWED_ORIGINS.includes(origin);
}

// Body size limit constant (32KB)
export const MAX_BODY_SIZE = 32768;
