import { z } from "zod";

// User messages capped at 500 chars (input limit). Assistant messages are
// generated by our own API so they can be longer — capped at 4096 to bound
// history size without rejecting legitimate multi-turn conversations.
const UserMessageSchema = z.object({
  role: z.literal("user"),
  content: z
    .string()
    .min(1)
    .max(500)
    .transform((s) => s.trim())
    .pipe(z.string().min(1)),
});

const AssistantMessageSchema = z.object({
  role: z.literal("assistant"),
  content: z
    .string()
    .min(1)
    .max(4096)
    .transform((s) => s.trim())
    .pipe(z.string().min(1)),
});

export const MessageSchema = z.discriminatedUnion("role", [
  UserMessageSchema,
  AssistantMessageSchema,
]);

export const RequestSchema = z.object({
  messages: z.array(MessageSchema).min(1).max(30),
});

export type ValidatedMessage = z.infer<typeof MessageSchema>;
export type ValidatedRequest = z.infer<typeof RequestSchema>;

export function validateRequest(
  body: unknown
): { success: true; data: ValidatedRequest } | { success: false; error: string } {
  const result = RequestSchema.safeParse(body);
  if (!result.success) {
    return { success: false, error: "invalid_request" };
  }
  return { success: true, data: result.data };
}

export function sanitizeMessages(messages: ValidatedMessage[]): ValidatedMessage[] {
  // Filter to only user/assistant (already enforced by schema, belt-and-suspenders)
  const filtered = messages.filter(
    (m) => m.role === "user" || m.role === "assistant"
  );
  // Trim to last 20 entries (10 conversation turns)
  return filtered.slice(-20);
}

// Exact origin whitelist for CORS — addresses review concern: all 3 reviewers flagged
// endsWith() as bypassable (e.g., "evil-jackcutrara.com" would pass).
// Uses URL parsing for safe comparison.
const ALLOWED_ORIGINS = [
  "https://jackcutrara.com",
  "https://www.jackcutrara.com",
];

// Cloudflare Pages project hostname. Only subdomains of this hostname
// (preview deployments of THIS project) pass CORS — not every *.pages.dev site.
// The "-5wl" random suffix is Cloudflare-assigned at project creation and is
// load-bearing: it prevents another Cloudflare Pages user from registering a
// colliding `portfolio.pages.dev` project and bypassing this check. If this
// project is ever renamed, update this constant in lockstep — do NOT shorten
// the suffix to a non-random form.
const PAGES_PREVIEW_SUFFIX = ".portfolio-5wl.pages.dev";

export function isAllowedOrigin(origin: string | null): boolean {
  if (!origin) return true; // No origin header = same-origin or non-browser
  let url: URL;
  try {
    url = new URL(origin);
  } catch {
    return false; // Malformed origin
  }
  // Allow localhost for development
  if (url.hostname === "localhost" || url.hostname === "127.0.0.1") return true;
  // Allow preview subdomains of the project's pages.dev hostname (https only).
  // Require exactly one non-empty label before the suffix — this rejects the
  // apex `portfolio-5wl.pages.dev` and empty-label forms like
  // `..portfolio-5wl.pages.dev` that some URL parsers normalize inconsistently.
  if (url.protocol === "https:" && url.hostname.endsWith(PAGES_PREVIEW_SUFFIX)) {
    const prefix = url.hostname.slice(0, -PAGES_PREVIEW_SUFFIX.length);
    if (prefix.length > 0 && !prefix.endsWith(".")) return true;
  }
  return ALLOWED_ORIGINS.includes(origin);
}

// Body size limit constant (32KB)
export const MAX_BODY_SIZE = 32768;
